from enum import StrEnum


class States(StrEnum):
    WELCOME = "1"
    FOLLOW_NODE_OPERATOR = "2"
    UNFOLLOW_NODE_OPERATOR = "3"
    FOLLOWED_EVENTS = "4"
    ADMIN = "5"
    ADMIN_BROADCAST = "6"
    ADMIN_BROADCAST_MESSAGE_ALL = "7"
    ADMIN_BROADCAST_SELECT_NO = "8"
    ADMIN_BROADCAST_MESSAGE_SELECTED = "9"


class Callback(StrEnum):
    FOLLOW_TO_NODE_OPERATOR = "1"
    UNFOLLOW_FROM_NODE_OPERATOR = "2"
    FOLLOWED_EVENTS = "3"
    BACK = "4"
    ADMIN = "5"
    ADMIN_SUBSCRIPTIONS = "6"
    ADMIN_BROADCAST = "7"
    ADMIN_BROADCAST_ALL = "8"
    ADMIN_BROADCAST_BY_NO = "9"
