version: '3.8'

services:
  csm-sentinel:
    build: .
    container_name: csm-sentinel
    env_file: .env
    volumes:
      - csm-sentinel-persistence:/app/.storage
    restart: unless-stopped

volumes:
  csm-sentinel-persistence:
